### PR TITLE
Create functions for mask creation that return a ndarray

### PR DESCRIPTION
**Pull request by jojoelfe**
Hi,

I was wondering if it would be possible to slightly refactor the mask creation so that the underlying functions return the numpy array instead of writing to an mrcfile. This makes it easier to use ttmask as a library. 

Here is my attempt to do it (which I thought could be done easily by Copilot but that turned out to be a huge mistake). I've added some basic tests too, but I do think they could be neater.

Feel free to dismiss if you do not like it. Also happy to make any changes you suggest.

### CODE REVIEW

**Comment by alisterburt** [comment]
Love this! I'm all for it - @milesagraham what do you think?

**Comment by milesagraham** [comment]
Hi, this sounds good to me too and makes sense when looking for integration with other teamtomo bits. I've taken a brief look but need to spend time on Friday dedicated to understanding your code (want to keep an understanding of what each line in the ttmask code is doing, for my own benefit as a rookie). Thank you very much for contributing and improving it! 

@alisterburt do you want to squash/merge this now?

**Comment by alisterburt** [comment]
@milesagraham go ahead! 🙂

**Comment by milesagraham** [comment]
Hi, I've gone through all of the changes and understand what you are doing, thanks! Makes so much sense to do this

**Pull request merged**
